# Generated by Django 4.2.7 on 2025-09-23 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('author', models.CharField(help_text='Author of the book', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('published_date', models.DateField(help_text='Date when the book was published')),
                ('description', models.TextField(blank=True, help_text='Description of the book', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
