# Generated by Django 4.2.7 on 2025-09-23 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('country', models.CharField(help_text='Country code', max_length=10)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('humidity', models.IntegerField(help_text='Humidity percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.FloatField(help_text='Atmospheric pressure in hPa', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(1200)])),
                ('weather_main', models.CharField(help_text='Main weather condition (e.g., Rain, Snow, Clear)', max_length=50)),
                ('weather_description', models.CharField(help_text='Detailed weather description', max_length=100)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in m/s', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('visibility', models.IntegerField(blank=True, help_text='Visibility in meters', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['city', 'country'], name='external_ap_city_ebc900_idx'), models.Index(fields=['fetched_at'], name='external_ap_fetched_3163de_idx')],
            },
        ),
    ]
