# Generated by Django 4.2.7 on 2025-09-23 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.RemoveIndex(
            model_name='weatherdata',
            name='external_ap_city_ebc900_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherdata',
            name='external_ap_fetched_3163de_idx',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather_main',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='description',
            field=models.CharField(default='Clear sky', max_length=200),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='pressure',
            field=models.IntegerField(default=1013),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
